# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fotki-export}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gene Drabkin"]
  s.date = %q{2011-04-30}
  s.description = %q{Simple command line tool to download all your photos from Fotki.com}
  s.email = %q{gene.drabkin@gmail.com}
  s.executables = ["fotki-export"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Rakefile",
    "VERSION",
    "bin/fotki-export",
    "fotki-export.gemspec",
    "lib/fotki.rb"
  ]
  s.homepage = %q{https://github.com/cloocher/fotki-exporter}
  s.require_paths = ["lib"]
  s.requirements = ["none"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Fotki.com photo export tool.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<watir-webdriver>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<gemcutter>, [">= 0"])
      s.add_runtime_dependency(%q<watir-webdriver>, [">= 0.2.2"])
      s.add_runtime_dependency(%q<watir-webdriver>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<gemcutter>, [">= 0"])
    else
      s.add_dependency(%q<watir-webdriver>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<gemcutter>, [">= 0"])
      s.add_dependency(%q<watir-webdriver>, [">= 0.2.2"])
      s.add_dependency(%q<watir-webdriver>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<gemcutter>, [">= 0"])
    end
  else
    s.add_dependency(%q<watir-webdriver>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<gemcutter>, [">= 0"])
    s.add_dependency(%q<watir-webdriver>, [">= 0.2.2"])
    s.add_dependency(%q<watir-webdriver>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<gemcutter>, [">= 0"])
  end
end

